

# [[imports]]
#     path = "github.com/CaiJimmy/hugo-theme-stack/v4"



# config/_default/module.toml
theme = "hugo-theme-stack"

# [[imports]]
#      path = "headless-cms"

[outputs]
  home = ["HTML", "RSS", "HeadlessCMSConfig"]

# #挂载
# [module]
#   [[module.mounts]]
#     source = "themes/hugo-theme-stack/layouts/_shortcodes"
#     target = "layouts/shortcodes"
#   [[module.mounts]]
#     source = "themes/hugo-theme-stack/assets"
#     target = "assets"

[module]
  [module.hugoVersion]
    min = "0.119.0"
    extended = false
